/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sinaview.form.arquivo;


import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Danilo Caldas
 */
public class CadastroArquivo extends javax.swing.JInternalFrame {
  
      
    public ArquivoActionControl control;
            /** 
     * Creates new form CadastroArquivo
     */
    
    
    public CadastroArquivo(){
        initComponents();
        control = new ArquivoActionControl(this);
        
               
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldCaixa = new JFormattedTextField(NumberFormat.getNumberInstance());
        jYearChooserCadastroAno = new com.toedter.calendar.JYearChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPrestador = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListProcedimento = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPrestador = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaProcedimento = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonExcluirPrestador = new javax.swing.JButton();
        jButtonExcluirProcedimento = new javax.swing.JButton();

        jCheckBox13.setText("jCheckBox1");

        jCheckBox14.setText("jCheckBox2");

        jCheckBox15.setText("jCheckBox2");

        jCheckBox16.setText("jCheckBox2");

        jCheckBox17.setText("jCheckBox2");

        jCheckBox18.setText("jCheckBox2");

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Caixa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione os dados da caixa"));

        jLabel1.setText("Ano:");

        jLabel2.setText("Mês:");

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jLabel4.setText("Cor:");

        jComboBoxCor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Verde", "Azul", "Branco", "Amarelo", "Vermelho", " " }));

        jLabel3.setText("Nº Caixa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jYearChooserCadastroAno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCaixa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jYearChooserCadastroAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inclua Prestadore(s) e Procedimento(s)"));

        jListPrestador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jListPrestador.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "H.A.M", "H.S.I", "H.S.A", "H.S.R", "H.G.E", "H.ESPANHOL", "H.PORTUGUÊS", "H.A.NOVIS", "H.J.MOREIRA", "H.STª LUZIA", "H.EVANGÉLICO", "CICAN", "LIGA ALVARO", "ALCLIN", "CLIVAN", "BIOCHEK'UP", "CDTO", "CEHON", "CLILAB", "C.IMAGEM", "CLION", "COB", "CREASE", "CNCDO'S", "DIAGNOSON", "GMN", "HEMOBA", "IBOPC", "OFTALMOCENTER", "OFTALMODIAGNOSE", "S.S.PAULO", "SEMEGE", "ABRE", "A.R.PELEGRINO", "APAE", "AD. PEIXOTO", "ÁGUAS CLARAS", "F.BASAGLIA", "LIBERDADE", "NZINGA", "PERNAMBUÉS", "CELIA ROCHA", "CLPB", "CLIFIR", "CTCB", "CURE", "EDUARD. SABACK", "INST.GUANABARA", "JOAO RICARDO", "LUIS MEIRA LESSA", "NACPC", "ROSA GARCIA", "OSWALDO CAMARGO", "Mª CELIA ROCHA", "UFBA GARCIA", "RODRIGO DE MENEZES", "ION", "OUTROS" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListPrestador.setToolTipText("");
        jListPrestador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPrestadorMouseClicked(evt);
            }
        });
        jListPrestador.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListPrestadorValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListPrestador);

        jListProcedimento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jListProcedimento.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "ONCOLOGIA", "RADIOTERAPIA", "PSIQUIATRIA", "POSTECTOMIA", "AIH", "LITOTRIPSIA", "ODONTOLOGIA", "OFTALMOLOGIA", "RESSONÂNCIA", "TOMOGRAFIA", "CINTILOGRAFIA", "AC. MARCAPASSO", "AUDIOMETRIA", "SOROLOGIA", "OUTROS" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListProcedimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProcedimentoMouseClicked(evt);
            }
        });
        jListProcedimento.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListProcedimentoValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jListProcedimento);

        jLabel5.setText("Lista de Procedimento(s):");

        jLabel6.setText("Lista de Prestador(s):");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonFechar.setText("Fechar");

        jButtonCancelar.setText("Cancelar");

        jButtonSalvar.setText("Salvar");

        jButtonNovo.setText("Novo");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens que constarão nas caixa(s)"));

        jTextAreaPrestador.setColumns(1);
        jTextAreaPrestador.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPrestador);

        jTextAreaProcedimento.setColumns(20);
        jTextAreaProcedimento.setRows(5);
        jScrollPane2.setViewportView(jTextAreaProcedimento);

        jLabel7.setText("Prestador(s):");

        jLabel8.setText("Procedimento(s):");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jButtonExcluirPrestador.setText("Limpar Prestadores");

        jButtonExcluirProcedimento.setText("Limpar Procedimentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonExcluirProcedimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirPrestador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonExcluirPrestador, jButtonExcluirProcedimento});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFechar)
                .addGap(57, 57, 57)
                .addComponent(jButtonExcluirPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExcluirProcedimento)
                .addGap(47, 47, 47))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCancelar, jButtonFechar, jButtonNovo, jButtonSalvar});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonExcluirPrestador, jButtonExcluirProcedimento});

        setBounds(0, 0, 628, 599);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jListPrestadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPrestadorMouseClicked
//        StringBuffer buf =  new StringBuffer();
//        Object[] selectedValues = jListPrestador.getSelectedValues();
//        for (int i = 0; i < selectedValues.length; i++){
//            buf.append(selectedValues[i].toString()).append(",\n");
//        }
//        jTextAreaPrestador.append(buf.toString());
    }//GEN-LAST:event_jListPrestadorMouseClicked
    private void jListPrestadorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPrestadorValueChanged
    }//GEN-LAST:event_jListPrestadorValueChanged

    private void jListProcedimentoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListProcedimentoValueChanged
             
    }//GEN-LAST:event_jListProcedimentoValueChanged

    private void jListProcedimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProcedimentoMouseClicked
//        StringBuffer buf =  new StringBuffer();
//        Object[] selectedValues = jListProcedimento.getSelectedValues();
//        for (int i = 0; i < selectedValues.length; i++){
//            buf.append(selectedValues[i].toString()).append(",\n");
//        }
//        jTextAreaProcedimento.append(buf.toString());

    }//GEN-LAST:event_jListProcedimentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroArquivo().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CadastroArquivo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluirPrestador;
    private javax.swing.JButton jButtonExcluirProcedimento;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JComboBox jComboBoxCor;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JFormattedTextField jFormattedTextFieldCaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jListPrestador;
    private javax.swing.JList jListProcedimento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaPrestador;
    private javax.swing.JTextArea jTextAreaProcedimento;
    private com.toedter.calendar.JYearChooser jYearChooserCadastroAno;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getjButtonCancelar() {
        return jButtonCancelar;
    }

    public void setjButtonCancelar(javax.swing.JButton jButtonCancelar) {
        this.jButtonCancelar = jButtonCancelar;
    }

    public javax.swing.JButton getjButtonExcluirPrestador() {
        return jButtonExcluirPrestador;
    }

    public void setjButtonExcluirPrestador(javax.swing.JButton jButtonExcluirPrestador) {
        this.jButtonExcluirPrestador = jButtonExcluirPrestador;
    }

    public javax.swing.JButton getjButtonExcluirProcedimento() {
        return jButtonExcluirProcedimento;
    }

    public void setjButtonExcluirProcedimento(javax.swing.JButton jButtonExcluirProcedimento) {
        this.jButtonExcluirProcedimento = jButtonExcluirProcedimento;
    }

    public javax.swing.JButton getjButtonFechar() {
        return jButtonFechar;
    }

    public void setjButtonFechar(javax.swing.JButton jButtonFechar) {
        this.jButtonFechar = jButtonFechar;
    }

    public javax.swing.JButton getjButtonNovo() {
        return jButtonNovo;
    }

    public void setjButtonNovo(javax.swing.JButton jButtonNovo) {
        this.jButtonNovo = jButtonNovo;
    }

    public javax.swing.JButton getjButtonSalvar() {
        return jButtonSalvar;
    }

    public void setjButtonSalvar(javax.swing.JButton jButtonSalvar) {
        this.jButtonSalvar = jButtonSalvar;
    }

    public javax.swing.JComboBox getjComboBoxCor() {
        return jComboBoxCor;
    }

    public void setjComboBoxCor(javax.swing.JComboBox jComboBoxCor) {
        this.jComboBoxCor = jComboBoxCor;
    }

    public javax.swing.JComboBox getjComboBoxMes() {
        return jComboBoxMes;
    }

    public void setjComboBoxMes(javax.swing.JComboBox jComboBoxMes) {
        this.jComboBoxMes = jComboBoxMes;
    }

    public javax.swing.JFormattedTextField getjFormattedTextFieldCaixa() {
        return jFormattedTextFieldCaixa;
    }

    public void setjFormattedTextFieldCaixa(javax.swing.JFormattedTextField jFormattedTextFieldCaixa) {
        this.jFormattedTextFieldCaixa = jFormattedTextFieldCaixa;
    }

    public javax.swing.JList getjListPrestador() {
        return jListPrestador;
    }

    public void setjListPrestador(javax.swing.JList jListPrestador) {
        this.jListPrestador = jListPrestador;
    }

    public javax.swing.JList getjListProcedimento() {
        return jListProcedimento;
    }

    public void setjListProcedimento(javax.swing.JList jListProcedimento) {
        this.jListProcedimento = jListProcedimento;
    }

    public javax.swing.JTextArea getjTextAreaPrestador() {
        return jTextAreaPrestador;
    }

    public void setjTextAreaPrestador(javax.swing.JTextArea jTextAreaPrestador) {
        this.jTextAreaPrestador = jTextAreaPrestador;
    }

    public javax.swing.JTextArea getjTextAreaProcedimento() {
        return jTextAreaProcedimento;
    }

    public void setjTextAreaProcedimento(javax.swing.JTextArea jTextAreaProcedimento) {
        this.jTextAreaProcedimento = jTextAreaProcedimento;
    }

    public com.toedter.calendar.JYearChooser getjYearChooserCadastroAno() {
        return jYearChooserCadastroAno;
    }

    public void setjYearChooserCadastroAno(com.toedter.calendar.JYearChooser jYearChooserCadastroAno) {
        this.jYearChooserCadastroAno = jYearChooserCadastroAno;
    }

}
