/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sinaview.form.arquivo;


import java.text.NumberFormat;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Danilo Caldas
 */
public class ConsultaCaixa extends javax.swing.JInternalFrame {
    
    public ConsultaArquivoActionControl control;
    
    public ConsultaCaixa() {
        initComponents();
        control = new ConsultaArquivoActionControl(this);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonSair = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonPesquisarAno = new javax.swing.JRadioButton();
        jRadioButtonPesquisarAnoMEs = new javax.swing.JRadioButton();
        jRadioButtonContCaixa = new javax.swing.JRadioButton();
        jRadioButtonFolhaRosto = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jYearChooserAno = new com.toedter.calendar.JYearChooser();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldCaixa = new JFormattedTextField(NumberFormat.getNumberInstance());

        setClosable(true);
        setIconifiable(true);
        setTitle("Pesquisa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Arquivo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, null, new java.awt.Color(0, 0, 0)));

        jButtonSair.setText("Finalizar");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonOK.setText("Efetuar Pesquisa");
        jButtonOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKMouseClicked(evt);
            }
        });
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a forma de pesquisa"));

        Grupo1.add(jRadioButtonPesquisarAno);
        jRadioButtonPesquisarAno.setText("Pesquisar por Ano");
        jRadioButtonPesquisarAno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonPesquisarAnoMouseClicked(evt);
            }
        });

        Grupo1.add(jRadioButtonPesquisarAnoMEs);
        jRadioButtonPesquisarAnoMEs.setText("Pesquisar po Ano e Mês");

        Grupo1.add(jRadioButtonContCaixa);
        jRadioButtonContCaixa.setText("Pesquisar Conteúdo da Caixa");

        Grupo1.add(jRadioButtonFolhaRosto);
        jRadioButtonFolhaRosto.setText("Imprirmir Folha de Rosto da Caixa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPesquisarAno)
                    .addComponent(jRadioButtonPesquisarAnoMEs)
                    .addComponent(jRadioButtonContCaixa)
                    .addComponent(jRadioButtonFolhaRosto))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonPesquisarAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPesquisarAnoMEs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonContCaixa)
                .addGap(3, 3, 3)
                .addComponent(jRadioButtonFolhaRosto)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Insira os dados necessários"));

        jLabel1.setText("Ano:");

        jLabel2.setText("Mês:");

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JANEIRO", "FEVEREIRO", "MARÇO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO" }));

        jLabel3.setText("Nº Caixa:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jYearChooserAno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jFormattedTextFieldCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jFormattedTextFieldCaixa)
                    .addComponent(jYearChooserAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonOK, jButtonSair});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonOK, jButtonSair});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setBounds(0, 0, 535, 347);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
    
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jRadioButtonPesquisarAnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonPesquisarAnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPesquisarAnoMouseClicked

    private void jButtonOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOKMouseClicked

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
    
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCaixa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JFormattedTextField jFormattedTextFieldCaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonContCaixa;
    private javax.swing.JRadioButton jRadioButtonFolhaRosto;
    private javax.swing.JRadioButton jRadioButtonPesquisarAno;
    private javax.swing.JRadioButton jRadioButtonPesquisarAnoMEs;
    private com.toedter.calendar.JYearChooser jYearChooserAno;
    // End of variables declaration//GEN-END:variables

    public javax.swing.ButtonGroup getGrupo1() {
        return Grupo1;
    }

    public void setGrupo1(javax.swing.ButtonGroup Grupo1) {
        this.Grupo1 = Grupo1;
    }

    public javax.swing.JButton getjButtonOK() {
        return jButtonOK;
    }

    public void setjButtonOK(javax.swing.JButton jButtonOK) {
        this.jButtonOK = jButtonOK;
    }

    public javax.swing.JButton getjButtonSair() {
        return jButtonSair;
    }

    public void setjButtonSair(javax.swing.JButton jButtonSair) {
        this.jButtonSair = jButtonSair;
    }

    public javax.swing.JComboBox getjComboBoxMes() {
        return jComboBoxMes;
    }

    public void setjComboBoxMes(javax.swing.JComboBox jComboBoxMes) {
        this.jComboBoxMes = jComboBoxMes;
    }

    public javax.swing.JFormattedTextField getjFormattedTextFieldCaixa() {
        return jFormattedTextFieldCaixa;
    }

    public void setjFormattedTextFieldCaixa(javax.swing.JFormattedTextField jFormattedTextFieldCaixa) {
        this.jFormattedTextFieldCaixa = jFormattedTextFieldCaixa;
    }

    public javax.swing.JRadioButton getjRadioButtonContCaixa() {
        return jRadioButtonContCaixa;
    }

    public void setjRadioButtonContCaixa(javax.swing.JRadioButton jRadioButtonContCaixa) {
        this.jRadioButtonContCaixa = jRadioButtonContCaixa;
    }

    public javax.swing.JRadioButton getjRadioButtonFolhaRosto() {
        return jRadioButtonFolhaRosto;
    }

    public void setjRadioButtonFolhaRosto(javax.swing.JRadioButton jRadioButtonFolhaRosto) {
        this.jRadioButtonFolhaRosto = jRadioButtonFolhaRosto;
    }

    public javax.swing.JRadioButton getjRadioButtonPesquisarAno() {
        return jRadioButtonPesquisarAno;
    }

    public void setjRadioButtonPesquisarAno(javax.swing.JRadioButton jRadioButtonPesquisarAno) {
        this.jRadioButtonPesquisarAno = jRadioButtonPesquisarAno;
    }

    public javax.swing.JRadioButton getjRadioButtonPesquisarAnoMEs() {
        return jRadioButtonPesquisarAnoMEs;
    }

    public void setjRadioButtonPesquisarAnoMEs(javax.swing.JRadioButton jRadioButtonPesquisarAnoMEs) {
        this.jRadioButtonPesquisarAnoMEs = jRadioButtonPesquisarAnoMEs;
    }

    public com.toedter.calendar.JYearChooser getjYearChooserAno() {
        return jYearChooserAno;
    }

    public void setjYearChooserAno(com.toedter.calendar.JYearChooser jYearChooserAno) {
        this.jYearChooserAno = jYearChooserAno;
    }
}
